name:                ch7
version:             0.1.0.0
github:              "kwanghoon/Lecture_EOPL_Exercise/ch7"
license:             BSD3
author:              "Kwanghoon Choi"
maintainer:          "lazyswamp@gmail.com"
copyright:           "2024 Kwanghoon Choi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kwanghoon/Lecture_EOPL_Exercise>

dependencies:
- base >= 4.7 && < 5
- yapb >= 0.2.3
- hspec
- containers

# ghc-options:
# - -Wall
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src

executables:
  checkedlang-exe:
    main:                Main.hs
    source-dirs:         
    - app/checkedlang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch7

tests:
  checkedlang-test:
    main:                Spec.hs
    source-dirs:         
    - test/checkedlang
    - app/checkedlang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch7
