name:                ch4
version:             0.1.0.0
github:              "kwanghoon/Lecture_EOPL_Exercise/ch4"
license:             BSD3
author:              "Kwanghoon Choi"
maintainer:          "lazyswamp@gmail.com"
copyright:           "2024 Kwanghoon Choi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kwanghoon/Lecture_EOPL_Exercise>

dependencies:
- base >= 4.7 && < 5
- yapb >= 0.2.3

library:
  source-dirs: src

executables:
  expref-exe:
    main:                Main.hs
    source-dirs:         app/explicitrefslang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4

  impref-exe:
    main:                Main.hs
    source-dirs:         app/implicitrefslang
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4    

tests:
  ch4-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch4
