name:                ch5
version:             0.1.0.0
github:              "githubuser/ch5"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ch5#readme>

dependencies:
- base >= 4.7 && < 5
- yapb >= 0.2.3
- hspec

library:
  source-dirs: src

executables:
  letreccps-exe:
    main:                Main.hs
    source-dirs:         app/letreccps
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch5

  exceptions-exe:
    main:                Main.hs
    source-dirs:         app/exceptions
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch5

  threads-exe:
    main:                Main.hs
    source-dirs:         app/threads
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch5

tests:
  letreccps-test:
    main:                Spec.hs
    source-dirs:         
    - test/letreccps
    - app/letreccps
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch5


  exceptions-test:
    main:                Spec.hs
    source-dirs:         
    - test/exceptions
    - app/exceptions
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch5    
